# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('b2a1d4dab03f699872d7075884870198_MTU0ODEwMjAxMi0xMS0xMyAxMTo1OToxNS4xNzY1MzE')
  end)
end
